name: run lint and unittest
run-name: code validation for ${{ github.event_name }} ${{ github.sha }}
on: push
jobs:
  check-dependencies:
    runs-on: self-hosted
    steps:
      - name: Check environment
        run: |
          which pylint
          pylint --version
          python3 --version
          python3 -m unittest --help
  pylint-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: run pylint
        run: pylint src/main.py
  unit-test-job:
    runs-on: self-hosted
    steps:
      - name: run unittest
        run: python3 -m unittest src/test_main.py 
  
