name: pylint
run-name: sami is pylinting
on: push
jobs:
  debug-job:
    runs-on: self-hosted
    steps:
      - name: Check environment
        run: |
          which pylint
          pylint --version
          python --version
          python -m unittest --help
  pylint-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: pylint main.py
  unit-test-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: python -m unittest test_main.py 
  
