name: jobs jobs
run-name: samis jobs
on: push
jobs:
  debug-job:
    runs-on: self-hosted
    steps:
      - name: Check environment
        run: |
          which pylint
          pylint --version
          python3 --version
          python3 -m unittest --help
      - name: List files
        run: ls -l
      - name: Checkout code
        uses: actions/checkout@v3
  pylint-job:
    runs-on: self-hosted
    steps:
      - name: run pylint
        run: pylint src/main.py
  unit-test-job:
    runs-on: self-hosted
    steps:
      - name: run unittest
        run: python3 -m unittest src/test_main.py 
  
