name: jobs jobs
run-name: samis jobs
on: push
jobs:
  debug-job:
    runs-on: self-hosted
    steps:
      - name: Check environment
        run: |
          which pylint
          pylint --version
          python3 --version
          python3 -m unittest --help
  pylint-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: pylint main.py
  unit-test-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: python -m unittest test_main.py 
  
